
name: Deployment with multiple environments

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - qa
          - prod
          - release

    steps:
      - name: Deployment to different environment
        run: echo "Deploying to ${{ matrix.environment }}"
